### ISSUE TITLE
Cannot play

### ISSUE THREAD

**Issue by laurenshoogendijk** [SeniorHeld/f1tv-rtmp#2]
Hey! 

Love the project! I can however not read the stream, both from ffmpeg and VLC:

```
[NULL @ 0x55e0d2235c40] Opening 'rtmp://redact.ed/live/f1tv' for reading                     
[rtmp @ 0x55e0d2236660] No default whitelist set                                                         
[tcp @ 0x55e0d2236e60] No default whitelist set                                                          
[rtmp @ 0x55e0d2236660] Handshaking...                                                                   
[rtmp @ 0x55e0d2236660] Type answer 3                                                                    
[rtmp @ 0x55e0d2236660] Server version 13.14.10.13                                                       
[rtmp @ 0x55e0d2236660] Proto = rtmp, path = /live/f1tv, app = live, fname = f1tv                        
[rtmp @ 0x55e0d2236660] Window acknowledgement size = 5000000                                            
[rtmp @ 0x55e0d2236660] Max sent, unacked = 5000000                                                      
[rtmp @ 0x55e0d2236660] New incoming chunk size = 4096                                                   
[rtmp @ 0x55e0d2236660] Creating stream...                                                               
[rtmp @ 0x55e0d2236660] Sending play command for 'f1tv'                                                  
[rtmp @ 0x55e0d2236660] Deleting stream... 
```

I use a docker-compose file for running the container:

```
version: "3"

services:
  f1tv:
    container_name: f1tv
    image: htobi02/f1tv:latest
    ports:
      - "1935:1935/tcp"
    environment:
      F1TV_EMAIL: '********'
      F1TV_PASSWORD: ''********'
      LANGUAGE: 'eng'
      LIVE: 'true'
      RECORD: 'false'
    volumes:
      - '/data/docker/f1tv/record/:/record'
    restart: unless-stopped
```

I only get the following lines after canceling the 'Sending play command':

```
f1tv    | 159.69.27.108 [11/Mar/2022:15:25:16 +0100] PLAY "live" "f1tv" "" - 380 436 "" "LNX 9,0,124,2" (4s)
f1tv    | /app/f1tv.sh: line 43: [[: https://ott-video-cf.formula1.com/f7xxxxc8cf81ac81/out/v1/0b7a9xxxx6d09d38cc9c/index.m3u8?kid=1042&exp=1647095117&ttl=1440&token=xxxxxxxx&start=2022-03-11T11:55:03+00:00: syntax error in expression (error token is "://ott-video-cf.formula1.com/f7xxxxc8cf81ac81/out/v1/0b7a9xxxxc6d09d38cc9c/index.m3u8?kid=1042&exp=1647095117&ttl=1440&token=xxxxxxxx&start=2022-03-11T11:55:03+00:00")
```

**Edit:** Using your provided dockerfile (with a slight tweak ; dutch instead of german):

```
f1tv-en_1     | ERROR: URL is null. Maybe there is no live stream?
f1tv-nl_1     | ERROR: URL is null. Maybe there is no live stream?
f1tv-fx_1     | ERROR: URL is null. Maybe there is no live stream?
```

**Comment by hTobi02** [comment]
Hi!
tbh, it worked perfectly fine for me today. I only got an English soundtrack instead of Dutch. But that was because the originalstream was only available in English. 
I try to rebuild the docker image. Can you try again then?

Edit: Sorry btw for late response

**Comment by laurenshoogendijk** [comment]
Hi, thanks for the quick reply :-)
Soundtrack sound logical, as the dutch soundtrack will only be added in July I think.
Yeah sure, just give me a heads-up when it's available, then I'll pull it!

**Comment by hTobi02** [comment]
I have now pushed the image to Docker Hub. Can you maybe try again tomorrow or with "LIVE=false"?

**Comment by laurenshoogendijk** [comment]
@SeniorHeld Unfortunately, no:

```
f1tv-en_1     | ERROR: URL is null. Maybe there is no live stream?
f1tv-nl_1     | ERROR: URL is null. Maybe there is no live stream?
f1tv-fx_1     | ERROR: URL is null. Maybe there is no live stream?
f1tv_f1tv-en_1 exited with code 0
f1tv_f1tv-nl_1 exited with code 0
f1tv_f1tv-fx_1 exited with code 0
```

```
# cat docker-compose.yml
version: '3.3'
services:
    f1tv-en:
        env_file:
            - .env
        environment:
            - LANGUAGE=eng
            - LIVE=false
            - RECORD=false
        image: 'htobi02/f1tv:${TAG:-latest}'
        labels:
          - "com.centurylinklabs.watchtower.scope=f1tv"
    f1tv-nl:
        env_file:
            - .env
        environment:
            - LANGUAGE=nld
            - LIVE=false
            - RECORD=false
        image: 'htobi02/f1tv:${TAG:-latest}'
        labels:
          - "com.centurylinklabs.watchtower.scope=f1tv"
    f1tv-fx:
        env_file:
            - .env
        environment:
            - LANGUAGE=fx
            - LIVE=false
            - RECORD=false
        image: 'htobi02/f1tv:${TAG:-latest}'
        labels:
          - "com.centurylinklabs.watchtower.scope=f1tv"

    watchtower:
        image: containrrr/watchtower
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
        command: --interval 30 --scope f1tv
        labels:
          - "com.centurylinklabs.watchtower.scope=f1tv"
```
